name: tokomiring_web

description: Toko Miring Ecommerce Web Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # =========================
  # FIREBASE
  # =========================
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.2

  # =========================
  # STATE MANAGEMENT
  # =========================
  provider: ^6.1.2

  # =========================
  # UI
  # =========================
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  animations: ^2.0.11
  flutter_staggered_grid_view: ^0.7.0
  lottie: ^3.1.2
  sidebarx: ^0.17.1
  data_table_2: ^2.5.15

  # =========================
  # REALTIME CHART
  # =========================
  fl_chart: ^0.69.0

  # =========================
  # IMAGE & FILE
  # =========================
  image_picker: ^1.1.2
  file_picker: ^8.1.2

  # =========================
  # UTILITIES
  # =========================
  intl: ^0.19.0
  uuid: ^4.5.1
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/